### ISSUE TITLE
Method not found Npgsql.NpgsqlDataReader Npgsql.NpgsqlCommand.ExecuteReader() error

### ISSUE THREAD

**Issue by evgenyshugaev** [rebus-org/Rebus.PostgreSql#27]
I need to use Rebus.PostgreSql with .net4 and npgsql 6.0.4.
As I know in Rebus.PostgreSql is used npgsql 4.1.6.
The trouble in difference betweeen method signatures NpgsqlCommand.ExecuteReader() from npgsql 4.1.6 and npgsql 6.0.4
And I've get an error: method not found Npgsql.NpgsqlDataReader Npgsql.NpgsqlCommand.ExecuteReader()

   at Rebus.PostgreSql.PostgreSqlMagic.GetTableNames(PostgresConnection connection)
   at Rebus.PostgreSql.Transport.PostgreSqlTransport.<CreateSchemaAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.PostgreSql.Transport.PostgreSqlTransport.<EnsureTableIsCreatedAsync>d__23.MoveNext()

   at Rebus.PostgreSql.Transport.PostgreSqlTransport.<EnsureTableIsCreatedAsync>d__23.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Internals.AsyncHelpers.CustomSynchronizationContext.<<Run>b__7_0>d.MoveNext()
   at Rebus.Internals.AsyncHelpers.CustomSynchronizationContext.Run()
   at Rebus.Internals.AsyncHelpers.RunSync(Func`1 task)
   at Rebus.PostgreSql.Transport.PostgreSqlTransport.EnsureTableIsCreated()
   at Rebus.Config.PostgreSqlTransportConfigurationExtensions.<>c__DisplayClass4_0.<Configure>b__0(IResolutionContext context)
   at Rebus.Injection.Injectionist.Resolver`1.InvokeResolver(IResolutionContext context)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()

Woud you upgrade npgsql 4.1.6 to npgsql 6.0.4 in Rebus.PostgreSql with .net4?

here is my code:

                     var connectionHelper = new PostgresConnectionHelper(connectionString);

				Bus = Configure.With(Activator)
						.Transport(t => t.UsePostgreSql(connectionHelper, SubscriptionsTable, queueName))
						.Routing(r => r.TypeBased().Map<string>(queueName))
						.Options(o =>
						{
							o.SetNumberOfWorkers(numberOfWorkers);
							o.SetMaxParallelism(maxParallelism);
							o.SetBackoffTimes(
								TimeSpan.FromMilliseconds(500),
								TimeSpan.FromMilliseconds(1000),
								TimeSpan.FromMilliseconds(2000),
								TimeSpan.FromMilliseconds(4000)
							);
						})
						.Subscriptions(s => s.StoreInPostgres(connectionString, SubscriptionsTable))  //StoreInSqlServer(connectionString, SubscriptionsTable))
						.Start();

**Comment by mookid8000** [comment]
I've updated it to Npgsql 6.0.4 - it's on NuGet.org as Rebus.Postgresql 8.0.0 in a few minutes.

Thanks for making me aware of this issue 🙂
